### ISSUE TITLE
HST Link Bug fixed?

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#119]
In the previous release (15.2.0 and 15.2.1 ) there was a fatal bug, in the class HSTLinkImpl. As already mentioned in the past releases.

**We are aware of a number of blocking issues present in the brXM 15.2.0 and 15.2.1 releases. We are working on fixing these issues and will release a new version as soon as possible.
We recommend that all customers do not upgrade to 15.2 until the next maintenance release (15.2.2) is available.**

Today I checked the release 15.2.2 but found no information about the fixed issue. Is the bug fixed in version 15.2.2? If yes, could you conclude the release notes.

https://xmdocumentation.bloomreach.com/about/release-notes/15/15.2.2-release-notes.html

**Comment by MPriess** [comment]
If this is not the right place to ask. I open a cases ticket.

**Comment by nvankampenhout** [comment]
Let me check with the engineering team.

**Comment by nvankampenhout** [comment]
Hi @MPriess ,

I believe you are referring to https://issues.onehippo.com/browse/CMS-15296, this was actually fixed in 15.2.1 but that release turned out to have a different blocking issue so we advised to wait for 15.2.2.

For clarity, we will update the 15.2.2 release notes shortly to make clear CMS-15296 has indeed been fixed. Apologies for the confusion!

Thanks,
Niels
