### ISSUE TITLE
BloomReach Relevance MySQL 8 compatibility

### ISSUE THREAD

**Issue by Nayels** [bloomreach/docs-feedback#55]
The requirements state that the version needed for 'BloomReach Relevance' is MySQL 5.6. Is the documentation up to date? 
[See link](https://documentation.bloomreach.com/12/library/enterprise/enterprise-features/targeting/data-stores/sql-data-store.html)

We are going to use MySQL 8 with all our BloomReach products and this is a huge blocker.

**Comment by nvankampenhout** [comment]
Hi @Nayels,

The most up-to-date system requirements are at https://documentation.bloomreach.com/12/library/about/system-requirements.html (for v12, since you linked to a v12 page) or at https://documentation.bloomreach.com/14/library/about/system-requirements.html (for the latest version 14). MySQL 8 is supported by brXM 14.

Looks like the page you linked to contains outdated information. I'll update it to point to the above system requirements page.

Thanks!

**Comment by nvankampenhout** [comment]
Updated:

- https://documentation.bloomreach.com/14/library/enterprise/enterprise-features/targeting/data-stores/sql-data-store.html
- https://documentation.bloomreach.com/13/library/enterprise/enterprise-features/targeting/data-stores/sql-data-store.html
- https://documentation.bloomreach.com/12/library/enterprise/enterprise-features/targeting/data-stores/sql-data-store.html

**Comment by Nayels** [comment]
Okay. Thanks for the clarification!
